" vim -u vimrc
set nocompatible
set nu
" search
set hls
set incsearch
set ignorecase
set smartcase
" Escape insert mode on jj
imap jj <Esc>
imap jk <Esc>
"" highlight line and column
set cursorline
set colorcolumn=80
""" SLOWDOWN!!!
set cursorcolumn
set listchars=tab:>-

syntax on

set list
"" speed up
set lazyredraw

set expandtab tabstop=4 shiftwidth=4 softtabstop=4

set background=dark

set iminsert=0
set imsearch=0

" show long lines rather than a column of "@"
set display+=lastline

colorscheme darkblue
set t_Co=256

"" Enable folding
set foldmethod=indent
set foldlevel=99
"" Enable folding with spacebar
nnoremap <space> za

nnoremap <C-p> :Explore<space>

"" key mapping for saving file, save
nnoremap <C-s> :w<CR>
inoremap <C-s> <Esc>l:w<CR>i
" Allow saving of files as sudo when I forgot to start vim using sudo.
cmap w!! w !sudo tee > /dev/null %

" no timeout on visual mode
set timeoutlen=1000 ttimeoutlen=0
